### ISSUE TITLE
Add instructions for improved powersaving

### ISSUE THREAD

**Issue by pandeiro** [pandeiro/arch-on-air#3]
There are ways to get battery life with Arch that is on par with Mac OS X. That information belongs here.

**Comment by shime** [comment]
@pandeiro what's the usual battery life you get?

**Comment by pandeiro** [comment]
@shime Have never measured it properly, and been in a while since I ran OS X on mine, but I remember my early impression was that it was ~1-1.5 hours less than what OS X got.

**Comment by aminb** [comment]
@pandeiro @shime I'm using [Powerdown](https://wiki.archlinux.org/index.php/Powerdown). There's also [Power management](https://wiki.archlinux.org/index.php/Power_management) on wiki. Have you guys read these, or do you use any of them?

**Comment by pandeiro** [comment]
@aminb Thanks for the info; I have seen the info in the wiki but I have not tested it myself so I am hesitant to include it here. If you have firsthand experience and want to include a recommendation somewhere in this writeup, I'd be happy to include it.

**Comment by ribmo** [comment]
I used [powertop](https://wiki.archlinux.org/index.php/Powertop) when I was running Arch on a MacBook air. I found it helped extend battery life.

**Comment by pandeiro** [comment]
OK, I've just added basic summaries for both powedown and powertop. Having not used these myself, I'd appreciate any feedback or corrections.

**Comment by aminb** [comment]
@pandeiro `powerdown` has basically been an *install and forget* experience for me. It does [some](https://github.com/march-linux/powerdown/blob/master/powernow) useful adjustments based on whether you're running on [battery](https://github.com/march-linux/powerdown/blob/master/powerdown) or [AC](https://github.com/march-linux/powerdown/blob/master/powerup).

I'll try powertop soon and will try to submit a PR if it needs actions from user.
