### ISSUE TITLE
usb tethered phone install

### ISSUE THREAD

**Issue by axelav** [pandeiro/arch-on-air#4]
you mention tethering your mobile phone to install arch but I can't see how to do that without installing some packages, via https://wiki.archlinux.org/index.php/IPhone_Tethering

> To tether your iPhone over USB, you will need to install these packages: usbmuxd, libimobiledevice and ifuse.

it would be excellent to have more documentation about how that works.

**Comment by pandeiro** [comment]
Good point, @axelav. I only have experience with using an Android device, and in my case, just enabling USB tethering on the phone and plugging it in resulted in a working connection on eth0 or equivalent interface.

If someone with experience doing this with an iPhone could submit a PR, I'd be happy to include more detailed instructions for this point.

**Comment by axelav** [comment]
ah ok. from what I've been able to find, no one seems to have been able to do this. I ended up buying a thunderbolt -> ethernet adapter so we'll see how that goes. 

thanks for documenting your process. it's been very helpful so far!
