### ISSUE TITLE
dev/sda4?

### ISSUE THREAD

**Issue by SevenHong** [pandeiro/arch-on-air#9]
I was confused to see that I need to format "dev/sda4" in step 13. The way I understood is that:

before Arch installation:

sda1 EFI
sda2 Mac HD
sda3 Recovery

then we add two more partions, one for boot one for root, with an empty free space in between sda3 and boot:

128M free space <- you didn't mention this but I was also looking at [Arch's Macbook section page](https://wiki.archlinux.org/index.php/MacBook), so I left 128M space between boot and Recovery partition
boot <- you referred as sda5
root <- you referred as sda6

The mount section only mentioned sda5 and sda6 so it looks like sda1 ~ sda4 are what Mac OS has already, but mine only has three - EFI, Mac, Recovery.

What do you mean by sda4?

**Comment by eagleoneraptor** [comment]
@SevenHong You need to create an unformatted 128M partition before boot and root partitions, you're gonna format it in step "13. Launch Disk Utility in OS X".
